name: Publish Package to npmjs
on:
  push:
    branches: [ci-testing]
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          scope: '@layerzerolabs'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm test
      - run: npm publish --access=restricted
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
